- scripts/cdnify.js
Sometimes the `cdnify` step does not pick up the most recent version. This PR throws an error when the local version doesn't match the version returned by the npm registry. 
This version check only happens for the `latest` dist tag use case. The thinking here is rollback scenarios will still work fine if we want to deploy an older version for another dist tag like `active-production`.
Here's an example of this error being thrown:
> Update cdnify to error out when local version doesn't match

- package.json
- scripts/cdnify.js
We have been seeing ECONNRESET errors when using grabthar-cdnify most likely caused by the corporate proxy.
The sync process with cdnify can make many calls to the npm registry so having retry behavior seems like an easy solve. This PR adds the fetch-retry module to handle this for us: https://github.com/vercel/fetch-retry#rationale
> Use fetch-retry to deal with ECONNRESET errors with cdnify()

- scripts/activate.sh
- scripts/release.sh
This PR updates `grabthar-release` to update all non-prod dist tags to match whenever the "latest" dist tag is changed. It does so by adding a new `CDNIFY` environment variable option for `grabthar-activate` that can disable the cdnify step so it can be reused in `grabthar-release` for activating the non-prod dist tags.
The release process for SPB and the JS SDK involves manually updating non-prod dist-tags like `active-stage` with the first bundle so we can better validate in stage before shipping the second bundle to prod. This PR automates this manual step.
> Update release script to update non-prod dist tags

- scripts/activate.sh
- scripts/release.sh
This PR checks for an npm token. If one exists, it does not prompt for the 2FA, and passes it to `npm publish`.
> Add npm token check for 2FA prompt & npm publish

- scripts/validate-npm.sh
Currently the `npm whoami` check is failing when using an npm access token. This PR resolves the issue.
> Update npm validator script to account for tokens

- scripts/cdnify.js
The plan is to use `npm run cdnify --commitonly` from CI for updating the cdn folder in sdk-release and SPB.
> The commitonly cdnify option should not prompt for confirmation

- package.json
This PR updates the npm repo url, which is currently pointing to grumbler:
> Update npm repo url

- .github/workflows/publish.yml
- package.json
This PR fixes an `Cannot continue with unstaged or uncommitted changes` error that was caused by accidentally running `publish.mjs` twice by using a `publish` command in the `package.json` file. It also ignores `.mjs` files during `npm run babel`.
> Fix unstaged/uncommitted changes error

- .github/workflows/publish.yml
This PR uses `bahmutov/npm-install@v1` in the `publish` GitHub Actions workflow, instead of running the non-existent `npm run reinstall` command.
> Fix `publish` GitHub Actions workflow

- scripts/verify-npm-publish.mjs
This PR removes a newline character when updating `npm_public_registry_version`. Without this, `LOCAL_VERSION !== npm_public_registry_version` will continue to return `true`, and the `while` loop will eventually time out.
> Trim newline

- scripts/release.mjs
Instead of having to run separate commands or workflows for `latest` or `alpha` releases, this PR allows us to simply run a single command either locally or via GitHub Actions (i.e. `npm run release`). The type of release will be determined by which branch one is on. The default branch will yield a `patch` release on `latest`, and any other branch will yield a `prerelease` release on `alpha`. Forked repos will be blocked from publishing.
> Auto select dist-tag and version, and block publishing from forks

- scripts/release.mjs
Unfortunately, using the `--no-git-tag-version` option for `npm version` during `alpha` releases leaves unstaged/uncommitted changes in source control, which causes `grabthar-flatten` -> `grabthar-validate-git` to fail prior to publishing.
As an alternative to [removing `--no-git-tag-version` from `alpha` releases](https://github.com/krakenjs/grabthar-release/pull/28), we could stash the `version` change prior to running `grabthar-flatten`, then reapply it after `grabthar-flatten` finishes.
> Stash `version` change before running `flatten` for `alpha` releases

- scripts/release.mjs
This PR reverts the `--no-git-tag-version` changes that were made for `alpha` releases, because we lose the uncommitted version change in `package.json` prior to running `grabthar-verify-npm-publish` in two places:
1. https://github.com/paypal/paypal-smart-payment-buttons/blob/main/package.json#L64
2. https://github.com/krakenjs/grabthar-release/blob/main/scripts/release.mjs#L79
Additionally, the original aim was not to push any commits to one's feature branch during `alpha` releases, however, this is negated by the `Dist` commit here anyway:
1. https://github.com/paypal/paypal-smart-payment-buttons/blob/main/package.json#L48
> Revert `--no-git-tag-version` changes

- scripts/flatten.mjs
This PR removes git validation from `grabthar-flatten`.
> Remove git validation from `grabthar-flatten`

- package.json
This PR runs `git checkout ./scripts` after pushing and publishing, so as to avoid wiping out the output of `npm run babel` before publishing.
> fix: run babel before and check out `scripts` after publishing

- package.json
- scripts/release.mjs
This PR adds a dry run feature to show what would've happened while publishing an npm package without actually pushing anything to GitHub or publishing anything to npm. It logs any steps that aren't run for a better view of the complete process. It also reverts any changes to the `package.json` and `package-lock.json` files when done, so no manual cleanup is required. 
I've added local and CI support for this in **paypal-smart-payment-buttons** and **paypal-sdk-release**:
- https://github.com/paypal/paypal-smart-payment-buttons/pull/372
- https://github.com/paypal/paypal-sdk-release/pull/41
Here is an example screenshot of what it looks like:
> feat: add dry run option

- scripts/release.mjs
SPB uses [postpublish](https://github.com/paypal/paypal-smart-payment-buttons/blob/main/package.json#L63) to clean up after babel. Normally this is fine, but it wipes out our version bump during dry-runs:
This PR lays the groundwork for fixing this issue by getting `DRY_RUN` from `env`, and providing our own all-encompassing cleanup via `git clean -f && git checkout .`. Once an `if` condition using `DRY_RUN` has been added to `postpublish` in SPB, we will see the correct output during dry-runs:
> fix: get `DRY_RUN` from `env` and do final cleanup

- scripts/verify-npm-publish.mjs
Currently, if `npm_public_registry_version` does not immediately match `LOCAL_VERSION`, trimming the newline during the next reassignment of `npm_public_registry_version` will fail, because `trim()` is being called on an object. This can be fixed by accessing the `stdout` property of `npm_public_registry_version` before calling `trim()`. Here is a screenshot of the error before the fix:
> fix: access `stdout` property before `trim()`

- scripts/cdnify.js
- tests/cdnify.test.js
this will remove previously generated versioned folders created with the `--experimental-versioned-cdn` flag before creating a new one.
Because we have git history, we don't need to keep each versioned folder in the latest commit of the release repo. This would eventually get too big for git and for uploading assets to the CDNX tool
> feat: cleanup previous verisoned folders

- scripts/cdnify.js
Looks like this conditional should be checking the truthiness of `tarball`, not `versionInfo`
> fix: fix tarball guard case
